### ISSUE TITLE
连上后报错，无法显示设备的文件目录树，esp32最新micropython固件20200402

### ISSUE THREAD

**Issue by myhalo** [1zlab/EMP#4]
Welcome to 1ZLAB-EMPIDE!
Password: 
WebREPL connected
>>> ide.device_info()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'ide' isn't defined
>>> ide.memory_status()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'ide' isn't defined
>>> ide.tree()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'ide' isn't defined

**Comment by Singein** [comment]
你用的哪个版本的IDE呢， 
[测试](http://dev.1zlab.com) 还是 [非测试](http://emp.1zlab.com)

如果是测试版本的IDE， 请在mpy上安装并使用 `emp-ext`
<https://github.com/EasyMicroPython/EMP-EXT>

**Comment by l20031018** [comment]
I also got the same error.  The version of ide is http://emp.1zlab.com/.

**Comment by Singein** [comment]
sorry about that. I haven't maintained this project for a long time.  There are many reasons to stop maintenance.
so, I am not sure I could help you immediately.

But this is not meaning  I have totally gave up this project. I am also looking for a new way to contribute for the micropython commiunity. If it is possible, emp project will restart in the end of this year.
